### PR TITLE
Add topics to cover explanation

### PR DESCRIPTION
**Pull request by ingkebil**

### CODE REVIEW

**Comment by barrystokman** [comment]
I can't figure out what the purpose of these documents are. Is it still a a work in progress, and will it be more clear in the end?

To clarify: if I'm new to Clinical Genomics and someone tells me to read this, I would not be clear to me what I'm expected to do.

**Comment by ingkebil** [comment]
Thanks for the feedback!

I guess for this manual, we should add a default "how to test" section so it becomes clearer how to view the changes in a manual form.

This is not WIP. If I assign you to review, I expect (and got) a review :)

Could you clarify what you mean with: " if I'm new to Clinical Genomics and someone tells me to read this, " .. with 'this' do you mean this PR or the content of this document?

**Comment by barrystokman** [comment]
With 'this' I mean the content of the document. 

A document should have a **purpose** (if the reader is done reading it, a goal should have been accomplished), and I'm not sure what that goal is.

A document should have a well defined **target audience** (a car for instance can have several documents involved for different target audiences: the user manual for the owner, the technical manual for the mechanics, the brochure for potential new customers), and I'm not sure what that purpose is.
The words 'guide' and 'software development of team IT' and 'if you are new...' seem to imply new employees/developers, hence my remark 'if I'm new to CG and someone tells me to read this...'.

To the actual content: To get started the target audience is supposed to click a link to 'topics to cover' which leads to a document that says 'topics to cover' twice but contains no actual 'topics to cover' :) It contains another link to 'topics to cover', which really links to issues in the development repository, one of which (the one at the very bottom!) is called 'topics to cover'. What it does contain is an exercise, and I'm not sure why I or any other reader should do this exercise, it feels really out of context.

The introduction would be a great place to explicitly state what and who a document is for. For example:

"This document is a development guide for developers at Clinical Genomics. After reading this document you should be able to use Github for you development work: create a new branch, clone a repository to your local environment, commit your changes, push your changes to the remote repository, create a pull request, assign reviewers, merge with master."

I'm also a proponent of using a clearly explained use case instead of exercises. Exercises are very personal, because people have different levels of knowledge and expertise, and thus hold very little information. What I mean by that is that if you need to go back to a guide because you forgot something over time, or are unsure about things, you don't want to look at an exercise again, you want information.

A use case for instance would describe the steps a (fictional) developer would take to complete the goal of the document, making it as close to real life as possible. Instead of saying 'clone a branch to you local environment' say something like:

_"Sven just picked up a new user story. To start working on it, he first creates a new branch in Github. He decides to name his branch 'svens_branch'."_

\<screenshot>

_"To work on this branch, Sven clones it to his local environment using the CLI:"_

``` git clone -b svens_branch --single-branch git@github.com:Clinical-Genomics/cg.git```

Etc etc.

I have more ideas, let's discuss those later.

**Comment by ingkebil** [comment]
I'll close this one and remove the exercises instead.

**Pull request closed without merging**
