### PR TITLE
Update mkdocs.yml

### PR DESCRIPTION
**Pull request by henrikstranneheim**
Added the perl installation again.

### CODE REVIEW

**Comment by ingkebil** [comment]
Perlbrew is available on production servers. Adding installation instructions would make it seem you need to do something yourself to get perlbrew running for your $HOME dir. 
So, to avoid confusion, I've removed the installation instructions of perlbrew.

Two more remarks:
1. It would be nice to give users the same naming conventions for perlbrew libraries as for conda environments.
1. We should could move this part closer to "how to start a project" way at the start of the manual. Because well: what you describe here is needed at the start of a project :) I can show you what I mean in another commit.

**Comment by ingkebil** [comment]
Ok, I now moved perlbrew to the where the conda explanation is. It seems to fit really well there, what do you think?

**Comment by henrikstranneheim** [comment]
Looks good!

**Comment by ingkebil** [comment]
Published. Should be live in a couple of minutes.

**Pull request merged**
