### PR TITLE
feat(mip7_instructions): updates doc for validation of mip7

### PR DESCRIPTION
**Pull request by jemten**
How to view changes made to manual?

```
git clone -b <branch name> https://github.com/Clinical-Genomics/development.git
cd development
conda create -n D_mkdocs
source activate D_mkdocs
pip install -r requirements.txt
mkdocs serve
```

go to your browser: http://127.0.0.1:8000

### CODE REVIEW

**Comment by jemten** [comment]
@henrikstranneheim, the part regarding the paths to the validation data needs to be updated. I don't know where we keep that data at the moment

**Comment by ingkebil** [comment]
As this has got nothing to do with how to develop, I suggest we move this to amdoc 1203 instead. What do you think?

**Comment by henrikstranneheim** [comment]
@jemten @ingkebil Made some changes please review again

**Comment by ingkebil** [comment]
As this part of the documentation is not even publishable, what about moving this to amdoc 1203?

**Comment by henrikstranneheim** [comment]
I have moved the stage instructions to 1203.

I could add these instructions to mkdoks under: "How do install and develop in MIP for rare disesase on hasta?" or something similar if you like. Or do you only want general information in the development guide and not specifics on each tool?

**Comment by ingkebil** [comment]
I would prefer to have one place we can check on how to and how MIP is installed. It looks like 1203 is the place to be for that.
What do you think?

**Comment by henrikstranneheim** [comment]
Yes, for production and stage, but not for development. That I think would be better documented in the development guide

**Comment by ingkebil** [comment]
How to develop with a tool would in general be put with the documentation of that tool, e.g. the main README.md of that tool. How does that sound?

**Comment by henrikstranneheim** [comment]
That is already part of MIPs README, this is docs for how we think one should install MIP on hasta development

**Comment by ingkebil** [comment]
The goal of this guide is to be a high level _public_ guide, much like https://thoughtbot.com/playbook . To keep it public is a way to keep it high level, system agnostic, and devout of tools specifics. It describes in a general fashion how we develop and with what tools we are doing that, not what tools we are developing.

In that context, it doesn't make sense to put tool specific development instructions in here that might reveal how our systems are set up.

I'll close this for now.

**Pull request closed without merging**
